-- Criação da tabela
CREATE TABLE nba_all_star_selections (
    year INT,
    conference VARCHAR(10),
    player_name VARCHAR(100),
    team VARCHAR(100),
    position VARCHAR(20),
    starter BOOLEAN
);

-- Inserções para o ano de 1990
INSERT INTO nba_all_star_selections VALUES
(1990, 'East', 'Isiah Thomas', 'Detroit Pistons', 'PG', TRUE),
(1990, 'East', 'Michael Jordan', 'Chicago Bulls', 'SG', TRUE),
(1990, 'East', 'Larry Bird', 'Boston Celtics', 'SF', TRUE),
(1990, 'East', 'Charles Barkley', 'Philadelphia 76ers', 'PF', TRUE),
(1990, 'East', 'Patrick Ewing', 'New York Knicks', 'C', TRUE),
(1990, 'East', 'Joe Dumars', 'Detroit Pistons', 'SG', FALSE),
(1990, 'East', 'Reggie Miller', 'Indiana Pacers', 'SG', FALSE),
(1990, 'East', 'Scottie Pippen', 'Chicago Bulls', 'SF', FALSE),
(1990, 'East', 'Dominique Wilkins', 'Atlanta Hawks', 'SF', FALSE),
(1990, 'East', 'Dennis Rodman', 'Detroit Pistons', 'PF', FALSE),
(1990, 'East', 'Kevin McHale', 'Boston Celtics', 'PF', FALSE),
(1990, 'East', 'Robert Parish', 'Boston Celtics', 'C', FALSE),
(1990, 'West', 'Magic Johnson', 'Los Angeles Lakers', 'PG', TRUE),
(1990, 'West', 'John Stockton', 'Utah Jazz', 'PG', TRUE),
(1990, 'West', 'James Worthy', 'Los Angeles Lakers', 'SF', TRUE),
(1990, 'West', 'Tom Chambers', 'Phoenix Suns', 'PF', TRUE),
(1990, 'West', 'Hakeem Olajuwon', 'Houston Rockets', 'C', TRUE),
(1990, 'West', 'Kevin Johnson', 'Phoenix Suns', 'PG', FALSE),
(1990, 'West', 'Fat Lever', 'Denver Nuggets', 'PG', FALSE),
(1990, 'West', 'Clyde Drexler', 'Portland Trail Blazers', 'SG', FALSE),
(1990, 'West', 'Chris Mullin', 'Golden State Warriors', 'SF', FALSE),
(1990, 'West', 'A.C. Green', 'Los Angeles Lakers', 'PF', FALSE),
(1990, 'West', 'David Robinson', 'San Antonio Spurs', 'C', FALSE),
(1990, 'West', 'Rolando Blackman', 'Dallas Mavericks', 'SG', FALSE);

-- Inserções para o ano de 1991

(1991, 'East', 'Joe Dumars', 'Detroit Pistons', 'SG', TRUE),
(1991, 'East', 'Michael Jordan', 'Chicago Bulls', 'SG', TRUE),
(1991, 'East', 'Charles Barkley', 'Philadelphia 76ers', 'PF', TRUE),
(1991, 'East', 'Larry Bird', 'Boston Celtics', 'SF', TRUE),
(1991, 'East', 'Patrick Ewing', 'New York Knicks', 'C', TRUE),
(1991, 'East', 'Kevin McHale', 'Boston Celtics', 'PF', FALSE),
(1991, 'East', 'Robert Parish', 'Boston Celtics', 'C', FALSE),
(1991, 'East', 'Scottie Pippen', 'Chicago Bulls', 'SF', FALSE),
(1991, 'East', 'Isiah Thomas', 'Detroit Pistons', 'PG', FALSE),
(1991, 'East', 'Brad Daugherty', 'Cleveland Cavaliers', 'C', FALSE),
(1991, 'East', 'Dennis Rodman', 'Detroit Pistons', 'PF', FALSE),
(1991, 'East', 'Reggie Lewis', 'Boston Celtics', 'SG', FALSE),
(1991, 'West', 'Magic Johnson', 'Los Angeles Lakers', 'PG', TRUE),
(1991, 'West', 'Kevin Johnson', 'Phoenix Suns', 'PG', TRUE),
(1991, 'West', 'Chris Mullin', 'Golden State Warriors', 'SF', TRUE),
(1991, 'West', 'Karl Malone', 'Utah Jazz', 'PF', TRUE),
(1991, 'West', 'David Robinson', 'San Antonio Spurs', 'C', TRUE),
(1991, 'West', 'Clyde Drexler', 'Portland Trail Blazers', 'SG', FALSE),
(1991, 'West', 'Tim Hardaway', 'Golden State Warriors', 'PG', FALSE),
(1991, 'West', 'John Stockton', 'Utah Jazz', 'PG', FALSE),
(1991, 'West', 'James Worthy', 'Los Angeles Lakers', 'SF', FALSE),
(1991, 'West', 'Terry Porter', 'Portland Trail Blazers', 'PG', FALSE),
(1991, 'West', 'Tom Chambers', 'Phoenix Suns', 'PF', FALSE),
(1991, 'West', 'A.C. Green', 'Los Angeles Lakers', 'PF', FALSE);

-- Inserções para o ano de 1992

(1992, 'East', 'Michael Jordan', 'Chicago Bulls', 'SG', TRUE),
(1992, 'East', 'Isiah Thomas', 'Detroit Pistons', 'PG', TRUE),
(1992, 'East', 'Scottie Pippen', 'Chicago Bulls', 'SF', TRUE),
(1992, 'East', 'Charles Barkley', 'Philadelphia 76ers', 'PF', TRUE),
(1992, 'East', 'Patrick Ewing', 'New York Knicks', 'C', TRUE),
(1992, 'East', 'Joe Dumars', 'Detroit Pistons', 'SG', FALSE),
(1992, 'East', 'Reggie Lewis', 'Boston Celtics', 'SG', FALSE),
(1992, 'East', 'Brad Daugherty', 'Cleveland Cavaliers', 'C', FALSE),
(1992, 'East', 'Larry Nance', 'Cleveland Cavaliers', 'PF', FALSE),
(1992, 'East', 'Dennis Rodman', 'Detroit Pistons', 'PF', FALSE),
(1992, 'East', 'Mark Price', 'Cleveland Cavaliers', 'PG', FALSE),
(1992, 'East', 'Detlef Schrempf', 'Indiana Pacers', 'SF', FALSE),
(1992, 'West', 'Magic Johnson', 'Los Angeles Lakers', 'PG', TRUE),
(1992, 'West', 'Clyde Drexler', 'Portland Trail Blazers', 'SG', TRUE),
(1992, 'West', 'Chris Mullin', 'Golden State Warriors', 'SF', TRUE),
(1992, 'West', 'Karl Malone', 'Utah Jazz', 'PF', TRUE),
(1992, 'West', 'David Robinson', 'San Antonio Spurs', 'C', TRUE),
(1992, 'West', 'Tim Hardaway', 'Golden State Warriors', 'PG', FALSE),
(1992, 'West', 'John Stockton', 'Utah Jazz', 'PG', FALSE),
(1992, 'West', 'Otis Thorpe', 'Houston Rockets', 'PF', FALSE),
(1992, 'West', 'James Worthy', 'Los Angeles Lakers', 'SF', FALSE),
(1992, 'West', 'Dan Majerle', 'Phoenix Suns', 'SG', FALSE),
(1992, 'West', 'Hakeem Olajuwon', 'Houston Rockets', 'C', FALSE),
(1992, 'West', 'Jeff Hornacek', 'Phoenix Suns', 'SG', FALSE);

-- Inserções para o ano de 1993

(1993, 'East', 'Isiah Thomas', 'Detroit Pistons', 'PG', TRUE),
(1993, 'East', 'Michael Jordan', 'Chicago Bulls', 'SG', TRUE),
(1993, 'East', 'Scottie Pippen', 'Chicago Bulls', 'SF', TRUE),
(1993, 'East', 'Larry Johnson', 'Charlotte Hornets', 'PF', TRUE),
(1993, 'East', 'Shaquille O''Neal', 'Orlando Magic', 'C', TRUE),
(1993, 'East', 'Joe Dumars', 'Detroit Pistons', 'SG', FALSE),
(1993, 'East', 'Mark Price', 'Cleveland Cavaliers', 'PG', FALSE),
(1993, 'East', 'Brad Daugherty', 'Cleveland Cavaliers', 'C', FALSE),
(1993, 'East', 'Larry Nance', 'Cleveland Cavaliers', 'PF', FALSE),
(1993, 'East', 'Detlef Schrempf', 'Indiana Pacers', 'SF', FALSE),
(1993, 'East', 'Patrick Ewing', 'New York Knicks', 'C', FALSE),
(1993, 'East', 'Dominique Wilkins', 'Atlanta Hawks', 'SF', FALSE),
(1993, 'West', 'John Stockton', 'Utah Jazz', 'PG', TRUE),
(1993, 'West', 'Clyde Drexler', 'Portland Trail Blazers', 'SG', TRUE),
(1993, 'West', 'Charles Barkley', 'Phoenix Suns', 'SF', TRUE),
(1993, 'West', 'Karl Malone', 'Utah Jazz', 'PF', TRUE),
(1993, 'West', 'David Robinson', 'San Antonio Spurs', 'C', TRUE),
(1993, 'West', 'Tim Hardaway', 'Golden State Warriors', 'PG', FALSE),
(1993, 'West', 'Dan Majerle', 'Phoenix Suns', 'SG', FALSE),
(1993, 'West', 'Shawn Kemp', 'Seattle SuperSonics', 'PF', FALSE),
(1993, 'West', 'Sean Elliott', 'San Antonio Spurs', 'SF', FALSE),
(1993, 'West', 'Hakeem Olajuwon', 'Houston Rockets', 'C', FALSE),
(1993, 'West', 'Danny Manning', 'Los Angeles Clippers', 'PF', FALSE);
 
-- Inserções para o ano de 1994
INSERT INTO nba_all_star_selections_1994 VALUES
(1994, 'East', 'Kenny Anderson', 'New Jersey Nets', 'PG', TRUE),
(1994, 'East', 'Joe Dumars', 'Detroit Pistons', 'SG', TRUE),
(1994, 'East', 'Scottie Pippen', 'Chicago Bulls', 'SF', TRUE),
(1994, 'East', 'Derrick Coleman', 'New Jersey Nets', 'PF', TRUE),
(1994, 'East', 'Shaquille O''Neal', 'Orlando Magic', 'C', TRUE), 
(1994, 'East', 'Mark Price', 'Cleveland Cavaliers', 'PG', FALSE),
(1994, 'East', 'Reggie Miller', 'Indiana Pacers', 'SG', FALSE),
(1994, 'East', 'Alonzo Mourning', 'Charlotte Hornets', 'C', FALSE),
(1994, 'East', 'Larry Nance', 'Cleveland Cavaliers', 'PF', FALSE),
(1994, 'East', 'Dominique Wilkins', 'Atlanta Hawks', 'SF', FALSE),
(1994, 'East', 'B.J. Armstrong', 'Chicago Bulls', 'PG', FALSE),
(1994, 'East', 'Mookie Blaylock', 'Atlanta Hawks', 'PG', FALSE),
(1994, 'East', 'Horace Grant', 'Chicago Bulls', 'PF', FALSE),
(1994, 'East', 'Larry Johnson', 'Charlotte Hornets', 'PF', FALSE),
(1994, 'East', 'Alonzo Mourning', 'Charlotte Hornets', 'C', FALSE),
(1994, 'East', 'Patrick Ewing', 'New York Knicks', 'C', FALSE),
(1994, 'East', 'Dominique Wilkins', 'Atlanta Hawks', 'SF', FALSE),
(1994, 'West', 'John Stockton', 'Utah Jazz', 'PG', TRUE),
(1994, 'West', 'Latrell Sprewell', 'Golden State Warriors', 'SG', TRUE),
(1994, 'West', 'Charles Barkley', 'Phoenix Suns', 'SF', TRUE),
(1994, 'West', 'Karl Malone', 'Utah Jazz', 'PF', TRUE),
(1994, 'West', 'Hakeem Olajuwon', 'Houston Rockets', 'C', TRUE),
(1994, 'West', 'Gary Payton', 'Seattle SuperSonics', 'PG', FALSE),
(1994, 'West', 'Mitch Richmond', 'Sacramento Kings', 'SG', FALSE),
(1994, 'West', 'Shawn Kemp', 'Seattle SuperSonics', 'PF', FALSE),
(1994, 'West', 'Clifford Robinson', 'Portland Trail Blazers', 'PF', FALSE),
(1994, 'West', 'David Robinson', 'San Antonio Spurs', 'C', FALSE),
(1994, 'West', 'Dikembe Mutombo', 'Denver Nuggets', 'C', FALSE).

-- Inserções para o ano de 1995
(1995, 'East', 'Anfernee "Penny" Hardaway', 'Orlando Magic', 'PG', TRUE),
(1995, 'East', 'Reggie Miller', 'Indiana Pacers', 'SG', TRUE),
(1995, 'East', 'Scottie Pippen', 'Chicago Bulls', 'SF', TRUE),
(1995, 'East', 'Charles Oakley', 'New York Knicks', 'PF', TRUE),
(1995, 'East', 'Shaquille O''Neal', 'Orlando Magic', 'C', TRUE),
(1995, 'East', 'B.J. Armstrong', 'Chicago Bulls', 'PG', FALSE),
(1995, 'East', 'Kenny Anderson', 'New Jersey Nets', 'PG', FALSE),
(1995, 'East', 'John Starks', 'New York Knicks', 'SG', FALSE),
(1995, 'East', 'Grant Hill', 'Detroit Pistons', 'SF', FALSE),
(1995, 'East', 'Larry Johnson', 'Charlotte Hornets', 'PF', FALSE),
(1995, 'East', 'Derrick Coleman', 'New Jersey Nets', 'PF', FALSE),
(1995, 'East', 'Patrick Ewing', 'New York Knicks', 'C', FALSE),
(1995, 'West', 'Jason Kidd', 'Dallas Mavericks', 'PG', TRUE),
(1995, 'West', 'Mitch Richmond', 'Sacramento Kings', 'SG', TRUE),
(1995, 'West', 'Latrell Sprewell', 'Golden State Warriors', 'SF', TRUE),
(1995, 'West', 'Karl Malone', 'Utah Jazz', 'PF', TRUE),
(1995, 'West', 'David Robinson', 'San Antonio Spurs', 'C', TRUE),
(1995, 'West', 'John Stockton', 'Utah Jazz', 'PG', FALSE),
(1995, 'West', 'Gary Payton', 'Seattle SuperSonics', 'PG', FALSE),
(1995, 'West', 'Clyde Drexler', 'Portland Trail Blazers', 'SG', FALSE),
(1995, 'West', 'Sean Elliott', 'San Antonio Spurs', 'SF', FALSE),
(1995, 'West', 'Shawn Kemp', 'Seattle SuperSonics', 'PF', FALSE),
(1995, 'West', 'Dikembe Mutombo', 'Denver Nuggets', 'C', FALSE),
(1995, 'West', 'Hakeem Olajuwon', 'Houston Rockets', 'C', FALSE);

-- Inserções para o ano 1996
(1996, 'East', 'Penny Hardaway', 'Orlando Magic', 'PG', TRUE),
(1996, 'East', 'Michael Jordan', 'Chicago Bulls', 'SG', TRUE),
(1996, 'East', 'Grant Hill', 'Detroit Pistons', 'SF', TRUE),
(1996, 'East', 'Scottie Pippen', 'Chicago Bulls', 'PF', TRUE),
(1996, 'East', 'Shaquille O''Neal', 'Orlando Magic', 'C', TRUE),
(1996, 'East', 'Anfernee Hardaway', 'Orlando Magic', 'PG', FALSE),
(1996, 'East', 'Terrell Brandon', 'Cleveland Cavaliers', 'PG', FALSE),
(1996, 'East', 'Reggie Miller', 'Indiana Pacers', 'SG', FALSE),
(1996, 'East', 'Glen Rice', 'Miami Heat', 'SF', FALSE),
(1996, 'East', 'Vin Baker', 'Milwaukee Bucks', 'PF', FALSE),
(1996, 'East', 'Derrick Coleman', 'Philadelphia 76ers', 'PF', FALSE),
(1996, 'East', 'Patrick Ewing', 'New York Knicks', 'C', FALSE),
(1996, 'West', 'Gary Payton', 'Seattle SuperSonics', 'PG', TRUE),
(1996, 'West', 'Clyde Drexler', 'Houston Rockets', 'SG', TRUE),
(1996, 'West', 'Charles Barkley', 'Phoenix Suns', 'SF', TRUE),
(1996, 'West', 'Karl Malone', 'Utah Jazz', 'PF', TRUE),
(1996, 'West', 'Hakeem Olajuwon', 'Houston Rockets', 'C', TRUE),
(1996, 'West', 'Jason Kidd', 'Dallas Mavericks', 'PG', FALSE),
(1996, 'West', 'Mitch Richmond', 'Sacramento Kings', 'SG', FALSE),
(1996, 'West', 'Detlef Schrempf', 'Seattle SuperSonics', 'SF', FALSE),
(1996, 'West', 'Sean Elliott', 'San Antonio Spurs', 'SF', FALSE),
(1996, 'West', 'David Robinson', 'San Antonio Spurs', 'C', FALSE),
(1996, 'West', 'Dikembe Mutombo', 'Denver Nuggets', 'C', FALSE);

-- Inserções para o ano 1997
(1997, 'East', 'Penny Hardaway', 'Orlando Magic', 'PG', TRUE),
(1997, 'East', 'Michael Jordan', 'Chicago Bulls', 'SG', TRUE),
(1997, 'East', 'Grant Hill', 'Detroit Pistons', 'SF', TRUE),
(1997, 'East', 'Shawn Kemp', 'Seattle SuperSonics', 'PF', TRUE),
(1997, 'East', 'Dikembe Mutombo', 'Atlanta Hawks', 'C', TRUE),
(1997, 'East', 'Terrell Brandon', 'Cleveland Cavaliers', 'PG', FALSE),
(1997, 'East', 'Tim Hardaway', 'Miami Heat', 'PG', FALSE),
(1997, 'East', 'Reggie Miller', 'Indiana Pacers', 'SG', FALSE),
(1997, 'East', 'Glen Rice', 'Charlotte Hornets', 'SF', FALSE),
(1997, 'East', 'Christian Laettner', 'Atlanta Hawks', 'PF', FALSE),
(1997, 'East', 'Chris Webber', 'Washington Bullets', 'PF', FALSE),
(1997, 'East', 'Patrick Ewing', 'New York Knicks', 'C', FALSE),
(1997, 'West', 'John Stockton', 'Utah Jazz', 'PG', TRUE),
(1997, 'West', 'Clyde Drexler', 'Houston Rockets', 'SG', TRUE),
(1997, 'West', 'Charles Barkley', 'Houston Rockets', 'SF', TRUE),
(1997, 'West', 'Karl Malone', 'Utah Jazz', 'PF', TRUE),
(1997, 'West', 'Hakeem Olajuwon', 'Houston Rockets', 'C', TRUE),
(1997, 'West', 'Gary Payton', 'Seattle SuperSonics', 'PG', FALSE),
(1997, 'West', 'Mitch Richmond', 'Sacramento Kings', 'SG', FALSE),
(1997, 'West', 'Vin Baker', 'Milwaukee Bucks', 'PF', FALSE),
(1997, 'West', 'Detlef Schrempf', 'Seattle SuperSonics', 'SF', FALSE),
(1997, 'West', 'David Robinson', 'San Antonio Spurs', 'C', FALSE),
(1997, 'West', 'Shaquille O''Neal', 'Los Angeles Lakers', 'C', FALSE);

-- Inserções para o ano 1998

(1998, 'East', 'Tim Hardaway', 'Miami Heat', 'PG', TRUE),
(1998, 'East', 'Michael Jordan', 'Chicago Bulls', 'SG', TRUE),
(1998, 'East', 'Grant Hill', 'Detroit Pistons', 'SF', TRUE),
(1998, 'East', 'Shawn Kemp', 'Cleveland Cavaliers', 'PF', TRUE),
(1998, 'East', 'Dikembe Mutombo', 'Atlanta Hawks', 'C', TRUE),
(1998, 'East', 'Penny Hardaway', 'Orlando Magic', 'PG', FALSE),
(1998, 'East', 'Steve Smith', 'Atlanta Hawks', 'SG', FALSE),
(1998, 'East', 'Glen Rice', 'Charlotte Hornets', 'SF', FALSE),
(1998, 'East', 'Vin Baker', 'Milwaukee Bucks', 'PF', FALSE),
(1998, 'East', 'Jayson Williams', 'New Jersey Nets', 'C', FALSE),
(1998, 'East', 'Chris Webber', 'Washington Wizards', 'PF', FALSE),
(1998, 'East', 'Rick Smits', 'Indiana Pacers', 'C', FALSE),
(1998, 'West', 'Gary Payton', 'Seattle SuperSonics', 'PG', TRUE),
(1998, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(1998, 'West', 'Kevin Garnett', 'Minnesota Timberwolves', 'SF', TRUE),
(1998, 'West', 'Karl Malone', 'Utah Jazz', 'PF', TRUE),
(1998, 'West', 'Shaquille O''Neal', 'Los Angeles Lakers', 'C', TRUE),
(1998, 'West', 'Jason Kidd', 'Phoenix Suns', 'PG', FALSE),
(1998, 'West', 'Eddie Jones', 'Los Angeles Lakers', 'SG', FALSE),
(1998, 'West', 'Nick Van Exel', 'Los Angeles Lakers', 'PG', FALSE),
(1998, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', FALSE),
(1998, 'West', 'David Robinson', 'San Antonio Spurs', 'C', FALSE),
(1998, 'West', 'Antonio McDyess', 'Denver Nuggets', 'PF', FALSE).

-- Inserções para o ano 1999 (não houve All-Star Game devido ao lockout)
-- Inserções dos jogadores do All-Star Game 2000
INSERT INTO nba_all_star_selections VALUES
(2000, 'East', 'Allen Iverson', 'Philadelphia 76ers', 'PG', TRUE),
(2000, 'East', 'Eddie Jones', 'Charlotte Hornets', 'SG', TRUE),
(2000, 'East', 'Grant Hill', 'Detroit Pistons', 'SF', TRUE),
(2000, 'East', 'Antonio Davis', 'Indiana Pacers', 'PF', TRUE),
(2000, 'East', 'Alonzo Mourning', 'Miami Heat', 'C', TRUE),
(2000, 'East', 'Latrell Sprewell', 'New York Knicks', 'SG', FALSE),
(2000, 'East', 'Allan Houston', 'New York Knicks', 'SG', FALSE),
(2000, 'East', 'Ray Allen', 'Milwaukee Bucks', 'SG', FALSE),
(2000, 'East', 'Dale Davis', 'Indiana Pacers', 'PF', FALSE),
(2000, 'East', 'Theo Ratliff', 'Philadelphia 76ers', 'C', FALSE),
(2000, 'East', 'Glenn Robinson', 'Milwaukee Bucks', 'SF', FALSE),
(2000, 'West', 'Jason Kidd', 'Phoenix Suns', 'PG', TRUE),
(2000, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2000, 'West', 'Kevin Garnett', 'Minnesota Timberwolves', 'SF', TRUE),
(2000, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', TRUE),
(2000, 'West', 'Shaquille O''Neal', 'Los Angeles Lakers', 'C', TRUE),
(2000, 'West', 'Gary Payton', 'Seattle SuperSonics', 'PG', FALSE),
(2000, 'West', 'John Stockton', 'Utah Jazz', 'PG', FALSE),
(2000, 'West', 'Karl Malone', 'Utah Jazz', 'PF', FALSE),
(2000, 'West', 'Chris Webber', 'Sacramento Kings', 'PF', FALSE),
(2000, 'West', 'David Robinson', 'San Antonio Spurs', 'C', FALSE),
(2000, 'West', 'Michael Finley', 'Dallas Mavericks', 'SG', FALSE);


-- Inserções dos jogadores do All-Star Game 2001
INSERT INTO nba_all_star_selections VALUES
(2001, 'East', 'Allen Iverson', 'Philadelphia 76ers', 'PG', TRUE),
(2001, 'East', 'Eddie Jones', 'Miami Heat', 'SG', TRUE),
(2001, 'East', 'Vince Carter', 'Toronto Raptors', 'SF', TRUE),
(2001, 'East', 'Antonio Davis', 'Indiana Pacers', 'PF', TRUE),
(2001, 'East', 'Dikembe Mutombo', 'Atlanta Hawks', 'C', TRUE),
(2001, 'East', 'Ray Allen', 'Milwaukee Bucks', 'SG', FALSE),
(2001, 'East', 'Latrell Sprewell', 'New York Knicks', 'SG', FALSE),
(2001, 'East', 'Allan Houston', 'New York Knicks', 'SG', FALSE),
(2001, 'East', 'Glenn Robinson', 'Milwaukee Bucks', 'SF', FALSE),
(2001, 'East', 'Stephon Marbury', 'New Jersey Nets', 'PG', FALSE),
(2001, 'East', 'Theo Ratliff', 'Philadelphia 76ers', 'C', FALSE),
(2001, 'West', 'Jason Kidd', 'Phoenix Suns', 'PG', TRUE),
(2001, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2001, 'West', 'Chris Webber', 'Sacramento Kings', 'SF', TRUE),
(2001, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', TRUE),
(2001, 'West', 'Shaquille O''Neal', 'Los Angeles Lakers', 'C', TRUE),
(2001, 'West', 'Steve Francis', 'Houston Rockets', 'PG', FALSE),
(2001, 'West', 'Gary Payton', 'Seattle SuperSonics', 'PG', FALSE),
(2001, 'West', 'Karl Malone', 'Utah Jazz', 'PF', FALSE),
(2001, 'West', 'Kevin Garnett', 'Minnesota Timberwolves', 'SF', FALSE),
(2001, 'West', 'David Robinson', 'San Antonio Spurs', 'C', FALSE),
(2001, 'West', 'Peja Stojakovic', 'Sacramento Kings', 'SF', FALSE);

-- Inserções dos jogadores do All-Star Game 2002
INSERT INTO nba_all_star_selections VALUES
(2002, 'East', 'Allen Iverson', 'Philadelphia 76ers', 'PG', TRUE),
(2002, 'East', 'Michael Jordan', 'Washington Wizards', 'SG', TRUE),
(2002, 'East', 'Vince Carter', 'Toronto Raptors', 'SF', TRUE),
(2002, 'East', 'Antoine Walker', 'Boston Celtics', 'PF', TRUE),
(2002, 'East', 'Dikembe Mutombo', 'Philadelphia 76ers', 'C', TRUE),
(2002, 'East', 'Jason Kidd', 'New Jersey Nets', 'PG', FALSE),
(2002, 'East', 'Ray Allen', 'Milwaukee Bucks', 'SG', FALSE),
(2002, 'East', 'Paul Pierce', 'Boston Celtics', 'SF', FALSE),
(2002, 'East', 'Shareef Abdur-Rahim', 'Atlanta Hawks', 'SF', FALSE),
(2002, 'East', 'Jermaine O''Neal', 'Indiana Pacers', 'PF', FALSE),
(2002, 'East', 'Alonzo Mourning', 'Miami Heat', 'C', FALSE),
(2002, 'West', 'Steve Francis', 'Houston Rockets', 'PG', TRUE),
(2002, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2002, 'West', 'Kevin Garnett', 'Minnesota Timberwolves', 'SF', TRUE),
(2002, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', TRUE),
(2002, 'West', 'Shaquille O''Neal', 'Los Angeles Lakers', 'C', TRUE),
(2002, 'West', 'Gary Payton', 'Seattle SuperSonics', 'PG', FALSE),
(2002, 'West', 'Dirk Nowitzki', 'Dallas Mavericks', 'PF', FALSE),
(2002, 'West', 'Chris Webber', 'Sacramento Kings', 'PF', FALSE),
(2002, 'West', 'Karl Malone', 'Utah Jazz', 'PF', FALSE),
(2002, 'West', 'David Robinson', 'San Antonio Spurs', 'C', FALSE),
(2002, 'West', 'Peja Stojakovic', 'Sacramento Kings', 'SF', FALSE);

-- Inserções dos jogadores do All-Star Game 2003
INSERT INTO nba_all_star_selections VALUES
(2003, 'East', 'Allen Iverson', 'Philadelphia 76ers', 'PG', TRUE),
(2003, 'East', 'Michael Jordan', 'Washington Wizards', 'SG', TRUE),
(2003, 'East', 'Tracy McGrady', 'Orlando Magic', 'SF', TRUE),
(2003, 'East', 'Jermaine O''Neal', 'Indiana Pacers', 'PF', TRUE),
(2003, 'East', 'Ben Wallace', 'Detroit Pistons', 'C', TRUE),
(2003, 'East', 'Jason Kidd', 'New Jersey Nets', 'PG', FALSE),
(2003, 'East', 'Paul Pierce', 'Boston Celtics', 'SF', FALSE),
(2003, 'East', 'Antoine Walker', 'Boston Celtics', 'PF', FALSE),
(2003, 'East', 'Shareef Abdur-Rahim', 'Atlanta Hawks', 'SF', FALSE),
(2003, 'East', 'Brad Miller', 'Indiana Pacers', 'C', FALSE),
(2003, 'East', 'Jamal Mashburn', 'New Orleans Hornets', 'SF', FALSE),
(2003, 'West', 'Steve Francis', 'Houston Rockets', 'PG', TRUE),
(2003, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2003, 'West', 'Kevin Garnett', 'Minnesota Timberwolves', 'SF', TRUE),
(2003, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', TRUE),
(2003, 'West', 'Yao Ming', 'Houston Rockets', 'C', TRUE),
(2003, 'West', 'Gary Payton', 'Seattle SuperSonics', 'PG', FALSE),
(2003, 'West', 'Dirk Nowitzki', 'Dallas Mavericks', 'PF', FALSE),
(2003, 'West', 'Chris Webber', 'Sacramento Kings', 'PF', FALSE),
(2003, 'West', 'Peja Stojakovic', 'Sacramento Kings', 'SF', FALSE),
(2003, 'West', 'Shaquille O''Neal', 'Los Angeles Lakers', 'C', FALSE),
(2003, 'West', 'Stephon Marbury', 'Phoenix Suns', 'PG', FALSE);

-- Inserções dos jogadores do All-Star Game 2004
INSERT INTO nba_all_star_selections VALUES
(2004, 'East', 'Allen Iverson', 'Philadelphia 76ers', 'PG', TRUE),
(2004, 'East', 'Tracy McGrady', 'Orlando Magic', 'SG', TRUE),
(2004, 'East', 'Vince Carter', 'Toronto Raptors', 'SF', TRUE),
(2004, 'East', 'Jermaine O''Neal', 'Indiana Pacers', 'PF', TRUE),
(2004, 'East', 'Ben Wallace', 'Detroit Pistons', 'C', TRUE),
(2004, 'East', 'Jason Kidd', 'New Jersey Nets', 'PG', FALSE),
(2004, 'East', 'Paul Pierce', 'Boston Celtics', 'SF', FALSE),
(2004, 'East', 'Baron Davis', 'New Orleans Hornets', 'PG', FALSE),
(2004, 'East', 'Ron Artest', 'Indiana Pacers', 'SF', FALSE),
(2004, 'East', 'Kenyon Martin', 'New Jersey Nets', 'PF', FALSE),
(2004, 'East', 'Jamaal Magloire', 'New Orleans Hornets', 'C', FALSE),
(2004, 'West', 'Steve Francis', 'Houston Rockets', 'PG', TRUE),
(2004, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2004, 'West', 'Kevin Garnett', 'Minnesota Timberwolves', 'SF', TRUE),
(2004, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', TRUE),
(2004, 'West', 'Yao Ming', 'Houston Rockets', 'C', TRUE),
(2004, 'West', 'Shaquille O''Neal', 'Los Angeles Lakers', 'C', FALSE),
(2004, 'West', 'Sam Cassell', 'Minnesota Timberwolves', 'PG', FALSE),
(2004, 'West', 'Ray Allen', 'Seattle SuperSonics', 'SG', FALSE),
(2004, 'West', 'Andrei Kirilenko', 'Utah Jazz', 'SF', FALSE),
(2004, 'West', 'Peja Stojakovic', 'Sacramento Kings', 'SF', FALSE),
(2004, 'West', 'Brad Miller', 'Sacramento Kings', 'C', FALSE);

-- Inserções dos jogadores do All-Star Game 2005
INSERT INTO nba_all_star_selections VALUES
(2005, 'East', 'Allen Iverson', 'Philadelphia 76ers', 'PG', TRUE),
(2005, 'East', 'Dwyane Wade', 'Miami Heat', 'SG', TRUE),
(2005, 'East', 'LeBron James', 'Cleveland Cavaliers', 'SF', TRUE),
(2005, 'East', 'Grant Hill', 'Orlando Magic', 'PF', TRUE),
(2005, 'East', 'Shaquille O''Neal', 'Miami Heat', 'C', TRUE),
(2005, 'East', 'Gilbert Arenas', 'Washington Wizards', 'PG', FALSE),
(2005, 'East', 'Antawn Jamison', 'Washington Wizards', 'PF', FALSE),
(2005, 'East', 'Paul Pierce', 'Boston Celtics', 'SF', FALSE),
(2005, 'East', 'Zydrunas Ilgauskas', 'Cleveland Cavaliers', 'C', FALSE),
(2005, 'East', 'Ben Wallace', 'Detroit Pistons', 'C', FALSE),
(2005, 'East', 'Jermaine O''Neal', 'Indiana Pacers', 'PF', FALSE),
(2005, 'West', 'Steve Nash', 'Phoenix Suns', 'PG', TRUE),
(2005, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2005, 'West', 'Tracy McGrady', 'Houston Rockets', 'SF', TRUE),
(2005, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', TRUE),
(2005, 'West', 'Yao Ming', 'Houston Rockets', 'C', TRUE),
(2005, 'West', 'Ray Allen', 'Seattle SuperSonics', 'SG', FALSE),
(2005, 'West', 'Dirk Nowitzki', 'Dallas Mavericks', 'PF', FALSE),
(2005, 'West', 'Manu Ginobili', 'San Antonio Spurs', 'SG', FALSE),
(2005, 'West', 'Shawn Marion', 'Phoenix Suns', 'SF', FALSE),
(2005, 'West', 'Amar''e Stoudemire', 'Phoenix Suns', 'C', FALSE),
(2005, 'West', 'Rashard Lewis', 'Seattle SuperSonics', 'SF', FALSE);

-- Inserções dos jogadores do All-Star Game 2006
INSERT INTO nba_all_star_selections VALUES
(2006, 'East', 'Allen Iverson', 'Philadelphia 76ers', 'PG', TRUE),
(2006, 'East', 'Dwyane Wade', 'Miami Heat', 'SG', TRUE),
(2006, 'East', 'LeBron James', 'Cleveland Cavaliers', 'SF', TRUE),
(2006, 'East', 'Chris Bosh', 'Toronto Raptors', 'PF', TRUE),
(2006, 'East', 'Shaquille O''Neal', 'Miami Heat', 'C', TRUE),
(2006, 'East', 'Chauncey Billups', 'Detroit Pistons', 'PG', FALSE),
(2006, 'East', 'Richard Hamilton', 'Detroit Pistons', 'SG', FALSE),
(2006, 'East', 'Paul Pierce', 'Boston Celtics', 'SF', FALSE),
(2006, 'East', 'Ben Wallace', 'Detroit Pistons', 'C', FALSE),
(2006, 'East', 'Rasheed Wallace', 'Detroit Pistons', 'PF', FALSE),
(2006, 'East', 'Gilbert Arenas', 'Washington Wizards', 'PG', FALSE),
(2006, 'West', 'Steve Nash', 'Phoenix Suns', 'PG', TRUE),
(2006, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2006, 'West', 'Tracy McGrady', 'Houston Rockets', 'SF', TRUE),
(2006, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', TRUE),
(2006, 'West', 'Yao Ming', 'Houston Rockets', 'C', TRUE),
(2006, 'West', 'Dirk Nowitzki', 'Dallas Mavericks', 'PF', FALSE),
(2006, 'West', 'Pau Gasol', 'Memphis Grizzlies', 'PF', FALSE),
(2006, 'West', 'Shawn Marion', 'Phoenix Suns', 'SF', FALSE),
(2006, 'West', 'Elton Brand', 'Los Angeles Clippers', 'PF', FALSE),
(2006, 'West', 'Tony Parker', 'San Antonio Spurs', 'PG', FALSE),
(2006, 'West', 'Kevin Garnett', 'Minnesota Timberwolves', 'PF', FALSE);

-- Inserções dos jogadores do All-Star Game 2007
INSERT INTO nba_all_star_selections VALUES
(2007, 'East', 'Gilbert Arenas', 'Washington Wizards', 'PG', TRUE),
(2007, 'East', 'Dwyane Wade', 'Miami Heat', 'SG', TRUE),
(2007, 'East', 'LeBron James', 'Cleveland Cavaliers', 'SF', TRUE),
(2007, 'East', 'Chris Bosh', 'Toronto Raptors', 'PF', TRUE),
(2007, 'East', 'Shaquille O''Neal', 'Miami Heat', 'C', TRUE),
(2007, 'East', 'Chauncey Billups', 'Detroit Pistons', 'PG', FALSE),
(2007, 'East', 'Richard Hamilton', 'Detroit Pistons', 'SG', FALSE),
(2007, 'East', 'Caron Butler', 'Washington Wizards', 'SF', FALSE),
(2007, 'East', 'Dwight Howard', 'Orlando Magic', 'C', FALSE),
(2007, 'East', 'Jermaine O''Neal', 'Indiana Pacers', 'PF', FALSE),
(2007, 'East', 'Vince Carter', 'New Jersey Nets', 'SG', FALSE),
(2007, 'West', 'Steve Nash', 'Phoenix Suns', 'PG', TRUE),
(2007, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2007, 'West', 'Kevin Garnett', 'Minnesota Timberwolves', 'SF', TRUE),
(2007, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', TRUE),
(2007, 'West', 'Yao Ming', 'Houston Rockets', 'C', TRUE),
(2007, 'West', 'Allen Iverson', 'Denver Nuggets', 'PG', FALSE),
(2007, 'West', 'Carmelo Anthony', 'Denver Nuggets', 'SF', FALSE),
(2007, 'West', 'Dirk Nowitzki', 'Dallas Mavericks', 'PF', FALSE),
(2007, 'West', 'Amar''e Stoudemire', 'Phoenix Suns', 'PF', FALSE),
(2007, 'West', 'Shawn Marion', 'Phoenix Suns', 'SF', FALSE),
(2007, 'West', 'Carlos Boozer', 'Utah Jazz', 'PF', FALSE);

-- Inserções dos jogadores do All-Star Game 2008
INSERT INTO nba_all_star_selections VALUES
(2008, 'East', 'Jason Kidd', 'New Jersey Nets', 'PG', TRUE),
(2008, 'East', 'Dwyane Wade', 'Miami Heat', 'SG', TRUE),
(2008, 'East', 'LeBron James', 'Cleveland Cavaliers', 'SF', TRUE),
(2008, 'East', 'Kevin Garnett', 'Boston Celtics', 'PF', TRUE),
(2008, 'East', 'Dwight Howard', 'Orlando Magic', 'C', TRUE),
(2008, 'East', 'Chauncey Billups', 'Detroit Pistons', 'PG', FALSE),
(2008, 'East', 'Joe Johnson', 'Atlanta Hawks', 'SG', FALSE),
(2008, 'East', 'Paul Pierce', 'Boston Celtics', 'SF', FALSE),
(2008, 'East', 'Rasheed Wallace', 'Detroit Pistons', 'PF', FALSE),
(2008, 'East', 'Chris Bosh', 'Toronto Raptors', 'PF', FALSE),
(2008, 'East', 'Richard Hamilton', 'Detroit Pistons', 'SG', FALSE),
(2008, 'West', 'Allen Iverson', 'Denver Nuggets', 'PG', TRUE),
(2008, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2008, 'West', 'Carmelo Anthony', 'Denver Nuggets', 'SF', TRUE),
(2008, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', TRUE),
(2008, 'West', 'Yao Ming', 'Houston Rockets', 'C', TRUE),
(2008, 'West', 'Chris Paul', 'New Orleans Hornets', 'PG', FALSE),
(2008, 'West', 'Brandon Roy', 'Portland Trail Blazers', 'SG', FALSE),
(2008, 'West', 'David West', 'New Orleans Hornets', 'PF', FALSE),
(2008, 'West', 'Dirk Nowitzki', 'Dallas Mavericks', 'PF', FALSE),
(2008, 'West', 'Amar''e Stoudemire', 'Phoenix Suns', 'PF', FALSE),
(2008, 'West', 'Carlos Boozer', 'Utah Jazz', 'PF', FALSE);


-- Inserções dos jogadores do All-Star Game 2009
INSERT INTO nba_all_star_selections VALUES
(2009, 'East', 'Allen Iverson', 'Detroit Pistons', 'PG', TRUE),
(2009, 'East', 'Dwyane Wade', 'Miami Heat', 'SG', TRUE),
(2009, 'East', 'LeBron James', 'Cleveland Cavaliers', 'SF', TRUE),
(2009, 'East', 'Kevin Garnett', 'Boston Celtics', 'PF', TRUE),
(2009, 'East', 'Dwight Howard', 'Orlando Magic', 'C', TRUE),
(2009, 'East', 'Joe Johnson', 'Atlanta Hawks', 'SG', FALSE),
(2009, 'East', 'Jameer Nelson', 'Orlando Magic', 'PG', FALSE),
(2009, 'East', 'Devin Harris', 'New Jersey Nets', 'PG', FALSE),
(2009, 'East', 'Danny Granger', 'Indiana Pacers', 'SF', FALSE),
(2009, 'East', 'Paul Pierce', 'Boston Celtics', 'SF', FALSE),
(2009, 'East', 'Chris Bosh', 'Toronto Raptors', 'PF', FALSE),
(2009, 'West', 'Chris Paul', 'New Orleans Hornets', 'PG', TRUE),
(2009, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2009, 'West', 'Amar''e Stoudemire', 'Phoenix Suns', 'PF', TRUE),
(2009, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', TRUE),
(2009, 'West', 'Yao Ming', 'Houston Rockets', 'C', TRUE),
(2009, 'West', 'Brandon Roy', 'Portland Trail Blazers', 'SG', FALSE),
(2009, 'West', 'Tony Parker', 'San Antonio Spurs', 'PG', FALSE),
(2009, 'West', 'Dirk Nowitzki', 'Dallas Mavericks', 'PF', FALSE),
(2009, 'West', 'Shaquille O''Neal', 'Phoenix Suns', 'C', FALSE),
(2009, 'West', 'Pau Gasol', 'Los Angeles Lakers', 'PF', FALSE),
(2009, 'West', 'David West', 'New Orleans Hornets', 'PF', FALSE);

-- Inserções dos jogadores do All-Star Game 2010
INSERT INTO nba_all_star_selections VALUES
(2010, 'East', 'Allen Iverson', 'Philadelphia 76ers', 'PG', TRUE),
(2010, 'East', 'Dwyane Wade', 'Miami Heat', 'SG', TRUE),
(2010, 'East', 'LeBron James', 'Cleveland Cavaliers', 'SF', TRUE),
(2010, 'East', 'Kevin Garnett', 'Boston Celtics', 'PF', TRUE),
(2010, 'East', 'Dwight Howard', 'Orlando Magic', 'C', TRUE),
(2010, 'East', 'Joe Johnson', 'Atlanta Hawks', 'SG', FALSE),
(2010, 'East', 'Rajon Rondo', 'Boston Celtics', 'PG', FALSE),
(2010, 'East', 'Paul Pierce', 'Boston Celtics', 'SF', FALSE),
(2010, 'East', 'Gerald Wallace', 'Charlotte Bobcats', 'SF', FALSE),
(2010, 'East', 'Chris Bosh', 'Toronto Raptors', 'PF', FALSE),
(2010, 'East', 'Al Horford', 'Atlanta Hawks', 'C', FALSE),
(2010, 'West', 'Steve Nash', 'Phoenix Suns', 'PG', TRUE),
(2010, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2010, 'West', 'Carmelo Anthony', 'Denver Nuggets', 'SF', TRUE),
(2010, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', TRUE),
(2010, 'West', 'Amar''e Stoudemire', 'Phoenix Suns', 'C', TRUE),
(2010, 'West', 'Chris Paul', 'New Orleans Hornets', 'PG', FALSE),
(2010, 'West', 'Deron Williams', 'Utah Jazz', 'PG', FALSE),
(2010, 'West', 'Brandon Roy', 'Portland Trail Blazers', 'SG', FALSE),
(2010, 'West', 'Dirk Nowitzki', 'Dallas Mavericks', 'PF', FALSE),
(2010, 'West', 'Kevin Durant', 'Oklahoma City Thunder', 'SF', FALSE),
(2010, 'West', 'Pau Gasol', 'Los Angeles Lakers', 'PF', FALSE);

-- Inserções dos jogadores do All-Star Game 2011
INSERT INTO nba_all_star_selections VALUES
(2011, 'East', 'Derrick Rose', 'Chicago Bulls', 'PG', TRUE),
(2011, 'East', 'Dwyane Wade', 'Miami Heat', 'SG', TRUE),
(2011, 'East', 'LeBron James', 'Miami Heat', 'SF', TRUE),
(2011, 'East', 'Amar''e Stoudemire', 'New York Knicks', 'PF', TRUE),
(2011, 'East', 'Dwight Howard', 'Orlando Magic', 'C', TRUE),
(2011, 'East', 'Rajon Rondo', 'Boston Celtics', 'PG', FALSE),
(2011, 'East', 'Ray Allen', 'Boston Celtics', 'SG', FALSE),
(2011, 'East', 'Paul Pierce', 'Boston Celtics', 'SF', FALSE),
(2011, 'East', 'Kevin Garnett', 'Boston Celtics', 'PF', FALSE),
(2011, 'East', 'Chris Bosh', 'Miami Heat', 'PF', FALSE),
(2011, 'East', 'Al Horford', 'Atlanta Hawks', 'C', FALSE),
(2011, 'West', 'Chris Paul', 'New Orleans Hornets', 'PG', TRUE),
(2011, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2011, 'West', 'Kevin Durant', 'Oklahoma City Thunder', 'SF', TRUE),
(2011, 'West', 'Carmelo Anthony', 'Denver Nuggets', 'SF', TRUE),
(2011, 'West', 'Yao Ming', 'Houston Rockets', 'C', TRUE),
(2011, 'West', 'Deron Williams', 'Utah Jazz', 'PG', FALSE),
(2011, 'West', 'Russell Westbrook', 'Oklahoma City Thunder', 'PG', FALSE),
(2011, 'West', 'Manu Ginobili', 'San Antonio Spurs', 'SG', FALSE),
(2011, 'West', 'Dirk Nowitzki', 'Dallas Mavericks', 'PF', FALSE),
(2011, 'West', 'Pau Gasol', 'Los Angeles Lakers', 'PF', FALSE),
(2011, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', FALSE).

-- Inserções dos jogadores do All-Star Game 2012
INSERT INTO nba_all_star_selections VALUES
(2012, 'East', 'Derrick Rose', 'Chicago Bulls', 'PG', TRUE),
(2012, 'East', 'Dwyane Wade', 'Miami Heat', 'SG', TRUE),
(2012, 'East', 'LeBron James', 'Miami Heat', 'SF', TRUE),
(2012, 'East', 'Carmelo Anthony', 'New York Knicks', 'PF', TRUE),
(2012, 'East', 'Dwight Howard', 'Orlando Magic', 'C', TRUE),
(2012, 'East', 'Rajon Rondo', 'Boston Celtics', 'PG', FALSE),
(2012, 'East', 'Joe Johnson', 'Atlanta Hawks', 'SG', FALSE),
(2012, 'East', 'Luol Deng', 'Chicago Bulls', 'SF', FALSE),
(2012, 'East', 'Andre Iguodala', 'Philadelphia 76ers', 'SF', FALSE),
(2012, 'East', 'Chris Bosh', 'Miami Heat', 'PF', FALSE),
(2012, 'East', 'Roy Hibbert', 'Indiana Pacers', 'C', FALSE),
(2012, 'West', 'Chris Paul', 'Los Angeles Clippers', 'PG', TRUE),
(2012, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2012, 'West', 'Kevin Durant', 'Oklahoma City Thunder', 'SF', TRUE),
(2012, 'West', 'Blake Griffin', 'Los Angeles Clippers', 'PF', TRUE),
(2012, 'West', 'Andrew Bynum', 'Los Angeles Lakers', 'C', TRUE),
(2012, 'West', 'Russell Westbrook', 'Oklahoma City Thunder', 'PG', FALSE),
(2012, 'West', 'Tony Parker', 'San Antonio Spurs', 'PG', FALSE),
(2012, 'West', 'Steve Nash', 'Phoenix Suns', 'PG', FALSE),
(2012, 'West', 'Dirk Nowitzki', 'Dallas Mavericks', 'PF', FALSE),
(2012, 'West', 'LaMarcus Aldridge', 'Portland Trail Blazers', 'PF', FALSE),
(2012, 'West', 'Marc Gasol', 'Memphis Grizzlies', 'C', FALSE);

-- Inserções dos jogadores do All-Star Game 2013
INSERT INTO nba_all_star_selections VALUES
(2013, 'East', 'Rajon Rondo', 'Boston Celtics', 'PG', TRUE),
(2013, 'East', 'Dwyane Wade', 'Miami Heat', 'SG', TRUE),
(2013, 'East', 'LeBron James', 'Miami Heat', 'SF', TRUE),
(2013, 'East', 'Carmelo Anthony', 'New York Knicks', 'PF', TRUE),
(2013, 'East', 'Kevin Garnett', 'Boston Celtics', 'C', TRUE),
(2013, 'East', 'Jrue Holiday', 'Philadelphia 76ers', 'PG', FALSE),
(2013, 'East', 'Kyrie Irving', 'Cleveland Cavaliers', 'PG', FALSE),
(2013, 'East', 'Paul George', 'Indiana Pacers', 'SF', FALSE),
(2013, 'East', 'Luol Deng', 'Chicago Bulls', 'SF', FALSE),
(2013, 'East', 'Chris Bosh', 'Miami Heat', 'PF', FALSE),
(2013, 'East', 'Tyson Chandler', 'New York Knicks', 'C', FALSE),
(2013, 'West', 'Chris Paul', 'Los Angeles Clippers', 'PG', TRUE),
(2013, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2013, 'West', 'Kevin Durant', 'Oklahoma City Thunder', 'SF', TRUE),
(2013, 'West', 'Blake Griffin', 'Los Angeles Clippers', 'PF', TRUE),
(2013, 'West', 'Dwight Howard', 'Los Angeles Lakers', 'C', TRUE),
(2013, 'West', 'Tony Parker', 'San Antonio Spurs', 'PG', FALSE),
(2013, 'West', 'Russell Westbrook', 'Oklahoma City Thunder', 'PG', FALSE),
(2013, 'West', 'James Harden', 'Houston Rockets', 'SG', FALSE),
(2013, 'West', 'David Lee', 'Golden State Warriors', 'PF', FALSE),
(2013, 'West', 'Zach Randolph', 'Memphis Grizzlies', 'PF', FALSE),
(2013, 'West', 'LaMarcus Aldridge', 'Portland Trail Blazers', 'PF', FALSE);

-- Inserções dos jogadores do All-Star Game 2014
INSERT INTO nba_all_star_selections VALUES
(2014, 'East', 'Kyrie Irving', 'Cleveland Cavaliers', 'PG', TRUE),
(2014, 'East', 'Dwyane Wade', 'Miami Heat', 'SG', TRUE),
(2014, 'East', 'LeBron James', 'Miami Heat', 'SF', TRUE),
(2014, 'East', 'Paul George', 'Indiana Pacers', 'PF', TRUE),
(2014, 'East', 'Carmelo Anthony', 'New York Knicks', 'C', TRUE),
(2014, 'East', 'John Wall', 'Washington Wizards', 'PG', FALSE),
(2014, 'East', 'DeMar DeRozan', 'Toronto Raptors', 'SG', FALSE),
(2014, 'East', 'Joe Johnson', 'Brooklyn Nets', 'SG', FALSE),
(2014, 'East', 'Chris Bosh', 'Miami Heat', 'PF', FALSE),
(2014, 'East', 'Roy Hibbert', 'Indiana Pacers', 'C', FALSE),
(2014, 'East', 'Joakim Noah', 'Chicago Bulls', 'C', FALSE),
(2014, 'West', 'Stephen Curry', 'Golden State Warriors', 'PG', TRUE),
(2014, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2014, 'West', 'Kevin Durant', 'Oklahoma City Thunder', 'SF', TRUE),
(2014, 'West', 'Blake Griffin', 'Los Angeles Clippers', 'PF', TRUE),
(2014, 'West', 'Kevin Love', 'Minnesota Timberwolves', 'C', TRUE),
(2014, 'West', 'Damian Lillard', 'Portland Trail Blazers', 'PG', FALSE),
(2014, 'West', 'James Harden', 'Houston Rockets', 'SG', FALSE),
(2014, 'West', 'Tony Parker', 'San Antonio Spurs', 'PG', FALSE),
(2014, 'West', 'LaMarcus Aldridge', 'Portland Trail Blazers', 'PF', FALSE),
(2014, 'West', 'Dwight Howard', 'Houston Rockets', 'C', FALSE),
(2014, 'West', 'Dirk Nowitzki', 'Dallas Mavericks', 'PF', FALSE);

-- Inserções dos jogadores do All-Star Game 2015
INSERT INTO nba_all_star_selections VALUES
(2015, 'East', 'John Wall', 'Washington Wizards', 'PG', TRUE),
(2015, 'East', 'Kyle Lowry', 'Toronto Raptors', 'PG', TRUE),
(2015, 'East', 'LeBron James', 'Cleveland Cavaliers', 'SF', TRUE),
(2015, 'East', 'Carmelo Anthony', 'New York Knicks', 'PF', TRUE),
(2015, 'East', 'Pau Gasol', 'Chicago Bulls', 'C', TRUE),
(2015, 'East', 'Jeff Teague', 'Atlanta Hawks', 'PG', FALSE),
(2015, 'East', 'Jimmy Butler', 'Chicago Bulls', 'SG', FALSE),
(2015, 'East', 'Kyrie Irving', 'Cleveland Cavaliers', 'PG', FALSE),
(2015, 'East', 'Chris Bosh', 'Miami Heat', 'PF', FALSE),
(2015, 'East', 'Paul Millsap', 'Atlanta Hawks', 'PF', FALSE),
(2015, 'East', 'Al Horford', 'Atlanta Hawks', 'C', FALSE),
(2015, 'West', 'Stephen Curry', 'Golden State Warriors', 'PG', TRUE),
(2015, 'West', 'James Harden', 'Houston Rockets', 'SG', TRUE),
(2015, 'West', 'Klay Thompson', 'Golden State Warriors', 'SG', TRUE),
(2015, 'West', 'Anthony Davis', 'New Orleans Pelicans', 'PF', TRUE),
(2015, 'West', 'Marc Gasol', 'Memphis Grizzlies', 'C', TRUE),
(2015, 'West', 'Chris Paul', 'Los Angeles Clippers', 'PG', FALSE),
(2015, 'West', 'Russell Westbrook', 'Oklahoma City Thunder', 'PG', FALSE),
(2015, 'West', 'LaMarcus Aldridge', 'Portland Trail Blazers', 'PF', FALSE),
(2015, 'West', 'Tim Duncan', 'San Antonio Spurs', 'PF', FALSE),
(2015, 'West', 'Kevin Durant', 'Oklahoma City Thunder', 'SF', FALSE),
(2015, 'West', 'DeMarcus Cousins', 'Sacramento Kings', 'C', FALSE);

-- Inserções dos jogadores do All-Star Game 2016
INSERT INTO nba_all_star_selections VALUES
(2016, 'East', 'Kyle Lowry', 'Toronto Raptors', 'PG', TRUE),
(2016, 'East', 'Dwyane Wade', 'Miami Heat', 'SG', TRUE),
(2016, 'East', 'LeBron James', 'Cleveland Cavaliers', 'SF', TRUE),
(2016, 'East', 'Paul George', 'Indiana Pacers', 'PF', TRUE),
(2016, 'East', 'Carmelo Anthony', 'New York Knicks', 'PF', TRUE),
(2016, 'East', 'John Wall', 'Washington Wizards', 'PG', FALSE),
(2016, 'East', 'DeMar DeRozan', 'Toronto Raptors', 'SG', FALSE),
(2016, 'East', 'Isaiah Thomas', 'Boston Celtics', 'PG', FALSE),
(2016, 'East', 'Chris Bosh', 'Miami Heat', 'PF', FALSE),
(2016, 'East', 'Paul Millsap', 'Atlanta Hawks', 'PF', FALSE),
(2016, 'East', 'Andre Drummond', 'Detroit Pistons', 'C', FALSE),
(2016, 'West', 'Stephen Curry', 'Golden State Warriors', 'PG', TRUE),
(2016, 'West', 'Russell Westbrook', 'Oklahoma City Thunder', 'PG', TRUE),
(2016, 'West', 'Kobe Bryant', 'Los Angeles Lakers', 'SG', TRUE),
(2016, 'West', 'Kevin Durant', 'Oklahoma City Thunder', 'SF', TRUE),
(2016, 'West', 'Kawhi Leonard', 'San Antonio Spurs', 'SF', TRUE),
(2016, 'West', 'Chris Paul', 'Los Angeles Clippers', 'PG', FALSE),
(2016, 'West', 'James Harden', 'Houston Rockets', 'SG', FALSE),
(2016, 'West', 'Draymond Green', 'Golden State Warriors', 'PF', FALSE),
(2016, 'West', 'Anthony Davis', 'New Orleans Pelicans', 'PF', FALSE),
(2016, 'West', 'DeMarcus Cousins', 'Sacramento Kings', 'C', FALSE),
(2016, 'West', 'LaMarcus Aldridge', 'San Antonio Spurs', 'PF', FALSE);

-- Inserções dos jogadores do All-Star Game 2017
INSERT INTO nba_all_star_selections VALUES
(2017, 'East', 'Kyrie Irving', 'Cleveland Cavaliers', 'PG', TRUE),
(2017, 'East', 'DeMar DeRozan', 'Toronto Raptors', 'SG', TRUE),
(2017, 'East', 'LeBron James', 'Cleveland Cavaliers', 'SF', TRUE),
(2017, 'East', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'PF', TRUE),
(2017, 'East', 'Jimmy Butler', 'Chicago Bulls', 'SF', TRUE),
(2017, 'East', 'Isaiah Thomas', 'Boston Celtics', 'PG', FALSE),
(2017, 'East', 'John Wall', 'Washington Wizards', 'PG', FALSE),
(2017, 'East', 'Kyle Lowry', 'Toronto Raptors', 'PG', FALSE),
(2017, 'East', 'Kemba Walker', 'Charlotte Hornets', 'PG', FALSE),
(2017, 'East', 'Paul George', 'Indiana Pacers', 'SF', FALSE),
(2017, 'East', 'Kevin Love', 'Cleveland Cavaliers', 'PF', FALSE),
(2017, 'West', 'Stephen Curry', 'Golden State Warriors', 'PG', TRUE),
(2017, 'West', 'James Harden', 'Houston Rockets', 'SG', TRUE),
(2017, 'West', 'Kevin Durant', 'Golden State Warriors', 'SF', TRUE),
(2017, 'West', 'Kawhi Leonard', 'San Antonio Spurs', 'SF', TRUE),
(2017, 'West', 'Anthony Davis', 'New Orleans Pelicans', 'PF', TRUE),
(2017, 'West', 'Russell Westbrook', 'Oklahoma City Thunder', 'PG', FALSE),
(2017, 'West', 'Klay Thompson', 'Golden State Warriors', 'SG', FALSE),
(2017, 'West', 'Draymond Green', 'Golden State Warriors', 'PF', FALSE),
(2017, 'West', 'DeMarcus Cousins', 'Sacramento Kings', 'C', FALSE),
(2017, 'West', 'Marc Gasol', 'Memphis Grizzlies', 'C', FALSE),
(2017, 'West', 'Gordon Hayward', 'Utah Jazz', 'SF', FALSE);

-- Inserções dos jogadores do All-Star Game 2018
INSERT INTO nba_all_star_selections VALUES
(2018, 'Mixed', 'LeBron James', 'Cleveland Cavaliers', 'SF', TRUE),
(2018, 'Mixed', 'Stephen Curry', 'Golden State Warriors', 'PG', TRUE),
(2018, 'Mixed', 'Kevin Durant', 'Golden State Warriors', 'SF', TRUE),
(2018, 'Mixed', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'PF', TRUE),
(2018, 'Mixed', 'Joel Embiid', 'Philadelphia 76ers', 'C', TRUE),
(2018, 'Mixed', 'DeMar DeRozan', 'Toronto Raptors', 'SG', TRUE),
(2018, 'Mixed', 'Kyrie Irving', 'Boston Celtics', 'PG', TRUE),
(2018, 'Mixed', 'Anthony Davis', 'New Orleans Pelicans', 'PF', TRUE),
(2018, 'Mixed', 'James Harden', 'Houston Rockets', 'SG', TRUE),
(2018, 'Mixed', 'DeMarcus Cousins', 'New Orleans Pelicans', 'C', FALSE),
(2018, 'Mixed', 'Damian Lillard', 'Portland Trail Blazers', 'PG', FALSE),
(2018, 'Mixed', 'Russell Westbrook', 'Oklahoma City Thunder', 'PG', FALSE),
(2018, 'Mixed', 'Jimmy Butler', 'Minnesota Timberwolves', 'SF', FALSE),
(2018, 'Mixed', 'Draymond Green', 'Golden State Warriors', 'PF', FALSE),
(2018, 'Mixed', 'Klay Thompson', 'Golden State Warriors', 'SG', FALSE),
(2018, 'Mixed', 'Karl-Anthony Towns', 'Minnesota Timberwolves', 'C', FALSE),
(2018, 'Mixed', 'Kyle Lowry', 'Toronto Raptors', 'PG', FALSE),
(2018, 'Mixed', 'Al Horford', 'Boston Celtics', 'C', FALSE),
(2018, 'Mixed', 'Bradley Beal', 'Washington Wizards', 'SG', FALSE),
(2018, 'Mixed', 'Victor Oladipo', 'Indiana Pacers', 'SG', FALSE),
(2018, 'Mixed', 'Kristaps Porzingis', 'New York Knicks', 'PF', FALSE),
(2018, 'Mixed', 'LaMarcus Aldridge', 'San Antonio Spurs', 'PF', FALSE),
(2018, 'Mixed', 'Paul George', 'Oklahoma City Thunder', 'SF', FALSE),
(2018, 'Mixed', 'Goran Dragic', 'Miami Heat', 'PG', FALSE).

-- Inserções dos jogadores do All-Star Game 2019
INSERT INTO nba_all_star_selections VALUES
(2019, 'Mixed', 'LeBron James', 'Los Angeles Lakers', 'SF', TRUE),
(2019, 'Mixed', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'PF', TRUE),
(2019, 'Mixed', 'Stephen Curry', 'Golden State Warriors', 'PG', TRUE),
(2019, 'Mixed', 'Kemba Walker', 'Charlotte Hornets', 'PG', TRUE),
(2019, 'Mixed', 'Joel Embiid', 'Philadelphia 76ers', 'C', TRUE),
(2019, 'Mixed', 'James Harden', 'Houston Rockets', 'SG', TRUE),
(2019, 'Mixed', 'Paul George', 'Oklahoma City Thunder', 'SF', TRUE),
(2019, 'Mixed', 'Kyrie Irving', 'Boston Celtics', 'PG', TRUE),
(2019, 'Mixed', 'Kawhi Leonard', 'Toronto Raptors', 'SF', TRUE),
(2019, 'Mixed', 'Kevin Durant', 'Golden State Warriors', 'SF', TRUE),
(2019, 'Mixed', 'Damian Lillard', 'Portland Trail Blazers', 'PG', FALSE),
(2019, 'Mixed', 'Anthony Davis', 'New Orleans Pelicans', 'PF', FALSE),
(2019, 'Mixed', 'Karl-Anthony Towns', 'Minnesota Timberwolves', 'C', FALSE),
(2019, 'Mixed', 'Klay Thompson', 'Golden State Warriors', 'SG', FALSE),
(2019, 'Mixed', 'Bradley Beal', 'Washington Wizards', 'SG', FALSE),
(2019, 'Mixed', 'Blake Griffin', 'Detroit Pistons', 'PF', FALSE),
(2019, 'Mixed', 'Nikola Jokic', 'Denver Nuggets', 'C', FALSE),
(2019, 'Mixed', 'Kyle Lowry', 'Toronto Raptors', 'PG', FALSE),
(2019, 'Mixed', 'Khris Middleton', 'Milwaukee Bucks', 'SF', FALSE),
(2019, 'Mixed', 'Russell Westbrook', 'Oklahoma City Thunder', 'PG', FALSE),
(2019, 'Mixed', 'D''Angelo Russell', 'Brooklyn Nets', 'PG', FALSE),
(2019, 'Mixed', 'Ben Simmons', 'Philadelphia 76ers', 'PG', FALSE),
(2019, 'Mixed', 'Nikola Vucevic', 'Orlando Magic', 'C', FALSE).

-- Inserções dos jogadores do All-Star Game 2020
INSERT INTO nba_all_star_selections VALUES
(2020, 'Mixed', 'LeBron James', 'Los Angeles Lakers', 'SF', TRUE),
(2020, 'Mixed', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'PF', TRUE),
(2020, 'Mixed', 'Anthony Davis', 'Los Angeles Lakers', 'PF', TRUE),
(2020, 'Mixed', 'Joel Embiid', 'Philadelphia 76ers', 'C', TRUE),
(2020, 'Mixed', 'Pascal Siakam', 'Toronto Raptors', 'PF', TRUE),
(2020, 'Mixed', 'Kawhi Leonard', 'Los Angeles Clippers', 'SF', TRUE),
(2020, 'Mixed', 'Luka Doncic', 'Dallas Mavericks', 'PG', TRUE),
(2020, 'Mixed', 'James Harden', 'Houston Rockets', 'SG', TRUE),
(2020, 'Mixed', 'Kemba Walker', 'Boston Celtics', 'PG', TRUE),
(2020, 'Mixed', 'Trae Young', 'Atlanta Hawks', 'PG', TRUE),
(2020, 'Mixed', 'Russell Westbrook', 'Houston Rockets', 'PG', FALSE),
(2020, 'Mixed', 'Jimmy Butler', 'Miami Heat', 'SF', FALSE),
(2020, 'Mixed', 'Chris Paul', 'Oklahoma City Thunder', 'PG', FALSE),
(2020, 'Mixed', 'Bam Adebayo', 'Miami Heat', 'C', FALSE),
(2020, 'Mixed', 'Rudy Gobert', 'Utah Jazz', 'C', FALSE),
(2020, 'Mixed', 'Jayson Tatum', 'Boston Celtics', 'SF', FALSE),
(2020, 'Mixed', 'Domantas Sabonis', 'Indiana Pacers', 'PF', FALSE),
(2020, 'Mixed', 'Donovan Mitchell', 'Utah Jazz', 'SG', FALSE),
(2020, 'Mixed', 'Brandon Ingram', 'New Orleans Pelicans', 'SF', FALSE),
(2020, 'Mixed', 'Kyle Lowry', 'Toronto Raptors', 'PG', FALSE),
(2020, 'Mixed', 'Ben Simmons', 'Philadelphia 76ers', 'PG', FALSE),
(2020, 'Mixed', 'Khris Middleton', 'Milwaukee Bucks', 'SF', FALSE),
(2020, 'Mixed', 'Damian Lillard', 'Portland Trail Blazers', 'PG', FALSE).

-- Inserções dos jogadores do All-Star Game 2021
INSERT INTO nba_all_star_selections VALUES
(2021, 'Mixed', 'LeBron James', 'Los Angeles Lakers', 'SF', TRUE),
(2021, 'Mixed', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'PF', TRUE),
(2021, 'Mixed', 'Stephen Curry', 'Golden State Warriors', 'PG', TRUE),
(2021, 'Mixed', 'Luka Doncic', 'Dallas Mavericks', 'PG', TRUE),
(2021, 'Mixed', 'Nikola Jokic', 'Denver Nuggets', 'C', TRUE),
(2021, 'Mixed', 'Joel Embiid', 'Philadelphia 76ers', 'C', TRUE),
(2021, 'Mixed', 'Kyrie Irving', 'Brooklyn Nets', 'PG', TRUE),
(2021, 'Mixed', 'Bradley Beal', 'Washington Wizards', 'SG', TRUE),
(2021, 'Mixed', 'Kawhi Leonard', 'Los Angeles Clippers', 'SF', TRUE),
(2021, 'Mixed', 'Jayson Tatum', 'Boston Celtics', 'SF', TRUE),
(2021, 'Mixed', 'Zion Williamson', 'New Orleans Pelicans', 'PF', FALSE),
(2021, 'Mixed', 'Jaylen Brown', 'Boston Celtics', 'SG', FALSE),
(2021, 'Mixed', 'James Harden', 'Brooklyn Nets', 'SG', FALSE),
(2021, 'Mixed', 'Damian Lillard', 'Portland Trail Blazers', 'PG', FALSE),
(2021, 'Mixed', 'Chris Paul', 'Phoenix Suns', 'PG', FALSE),
(2021, 'Mixed', 'Devin Booker', 'Phoenix Suns', 'SG', FALSE),
(2021, 'Mixed', 'Julius Randle', 'New York Knicks', 'PF', FALSE),
(2021, 'Mixed', 'Domantas Sabonis', 'Indiana Pacers', 'PF', FALSE),
(2021, 'Mixed', 'Donovan Mitchell', 'Utah Jazz', 'SG', FALSE),
(2021, 'Mixed', 'Rudy Gobert', 'Utah Jazz', 'C', FALSE),
(2021, 'Mixed', 'Zach LaVine', 'Chicago Bulls', 'SG', FALSE),
(2021, 'Mixed', 'Ben Simmons', 'Philadelphia 76ers', 'PG', FALSE).

-- Inserções dos jogadores do All-Star Game 2022
INSERT INTO nba_all_star_selections VALUES
(2022, 'Mixed', 'LeBron James', 'Los Angeles Lakers', 'SF', TRUE),
(2022, 'Mixed', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'PF', TRUE),
(2022, 'Mixed', 'Stephen Curry', 'Golden State Warriors', 'PG', TRUE),
(2022, 'Mixed', 'Nikola Jokic', 'Denver Nuggets', 'C', TRUE),
(2022, 'Mixed', 'DeMar DeRozan', 'Chicago Bulls', 'SG', TRUE),
(2022, 'Mixed', 'Joel Embiid', 'Philadelphia 76ers', 'C', TRUE),
(2022, 'Mixed', 'Ja Morant', 'Memphis Grizzlies', 'PG', TRUE),
(2022, 'Mixed', 'Andrew Wiggins', 'Golden State Warriors', 'SF', TRUE),
(2022, 'Mixed', 'Trae Young', 'Atlanta Hawks', 'PG', TRUE),
(2022, 'Mixed', 'Jayson Tatum', 'Boston Celtics', 'SF', TRUE),
(2022, 'Mixed', 'Devin Booker', 'Phoenix Suns', 'SG', FALSE),
(2022, 'Mixed', 'Chris Paul', 'Phoenix Suns', 'PG', FALSE),
(2022, 'Mixed', 'Karl-Anthony Towns', 'Minnesota Timberwolves', 'C', FALSE),
(2022, 'Mixed', 'Donovan Mitchell', 'Utah Jazz', 'SG', FALSE),
(2022, 'Mixed', 'Rudy Gobert', 'Utah Jazz', 'C', FALSE),
(2022, 'Mixed', 'Luka Doncic', 'Dallas Mavericks', 'PG', FALSE),
(2022, 'Mixed', 'Zach LaVine', 'Chicago Bulls', 'SG', FALSE),
(2022, 'Mixed', 'Fred VanVleet', 'Toronto Raptors', 'PG', FALSE),
(2022, 'Mixed', 'Darius Garland', 'Cleveland Cavaliers', 'PG', FALSE),
(2022, 'Mixed', 'Jimmy Butler', 'Miami Heat', 'SF', FALSE),
(2022, 'Mixed', 'Khris Middleton', 'Milwaukee Bucks', 'SF', FALSE),
(2022, 'Mixed', 'LaMelo Ball', 'Charlotte Hornets', 'PG', FALSE),
(2022, 'Mixed', 'Jarrett Allen', 'Cleveland Cavaliers', 'C', FALSE).
